sudo: false
os:
  - linux
dist: trusty
script: 
  - echo test > test.txt
  - echo ${DEMO_KEY} > demo.pem
  - scp -o StrictHostKeyChecking=no -i demo.pem test.txt ${DEMO_USER}@${DEMO_SRV}:${DEMO_PATH}
