language: java
sudo: required
os:
  - linux
services:
  - docker
dist: trusty
script: 
  - echo test > test.txt
  - echo ${DEMO_KEY} > demo.pem
  - scp -i demo.pem test.txt ${DEMO_USER}@${DEMO_SRV}:${DEMO_PATH}
