language: java
sudo: required
os:
  - linux
services:
  - docker
dist: trusty
install: 
    - pip install mkdocs
    - pip install mkdocs-material
script: 
  - ./gradlew buildDocker -PnoTest
  - chmod 777 deploy.sh
  - ./deploy.sh
